[package]
name = "types"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12.3"
prost = "0.13.3"
serde = "1.0.192"
sqlx = "0.8.2"

[build-dependencies]
tonic-build = "0.12"
prost-build = "0.13"


