[package]
version = "0.1.0"
name = "aggregation-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = { version = "3.0.0", features = ["verify"] }
sha2 = "0.10.8"
alloy-merkle-tree = "0.7.1"
alloy = "0.6.4"